### ISSUE TITLE
 Couldn't use following syntax to import it and assign the backed

### ISSUE THREAD

**Issue by molyswu** [AllanYiin/YoloV4#1]
Couldn't use following syntax to import it and assign the backed?
Tried to  pip install tridentx --upgrade ,python   pytorch_yolo.py
   trident 0.5.4
Using Pytorch backend.
Image Data Format: channels_first.
Image Channel Order: rgb.
Pytorch version:1.4.0.
Using pillow image backend.
Pillow version:6.2.2.
Traceback (most recent call last):
  File "pytorch_yolo.py", line 16, in <module>
    import trident as T
  File "  anaconda3/lib/python3.6/site-packages/trident/__init__.py", line 17, in <module>
    from . import backend
  from . import backend
  File "anaconda3/lib/python3.6/site-packages/trident/backend/__init__.py", line 8, in <module>
    from ..callbacks import *
  File "anaconda3/lib/python3.6/site-packages/trident/callbacks/__init__.py", line 354, in <module>
    from .visualization_callbacks import *
  File "anaconda3/lib/python3.6/site-packages/trident/callbacks/visualization_callbacks.py", line 12, in <module>
    from ..data.mask_common import label2color
  File "anaconda3/lib/python3.6/site-packages/trident/data/__init__.py", line 20, in <module>
    from .image_reader import ImageReader,ImageThread
  File "/home/ai/anaconda3/lib/python3.6/site-packages/trident/data/image_reader.py", line 8, in <module>
    from ..misc.ipython_utils import is_in_ipython, is_in_colab
  File "anaconda3/lib/python3.6/site-packages/trident/misc/__init__.py", line 3, in <module>
    from .visualization_utils import *
  File "anaconda3/lib/python3.6/site-packages/trident/misc/visualization_utils.py", line 17, in <module>
    names = [matplotlib.font_manager.FontProperties(fname=fname).get_name() for fname in fonts]
  File "anaconda3/lib/python3.6/site-packages/trident/misc/visualization_utils.py", line 17, in <listcomp>
    names = [matplotlib.font_manager.FontProperties(fname=fname).get_name() for fname in fonts]
  File "anaconda3/lib/python3.6/site-packages/matplotlib/font_manager.py", line 689, in get_name
    return get_font(findfont(self)).family_name

  File " anaconda3/lib/python3.6/site-packages/matplotlib/font_manager.p
    _kerning_factor=rcParams['text.kerning_factor'])
RuntimeError: In FT2Font: Can not load face.  Unknown file format.

**Comment by AllanYiin** [comment]
you should "pip install tridentx",  package name is registed by others

**Comment by AllanYiin** [comment]
It seems a issue because the font dispaly the bbox, cant u describe about your os, system language and ur prefered language.

**Comment by AllanYiin** [comment]
according to there article, it seems your matplotlib's font maybe corrupted, they are recommend enforce reinstall matplotlib can solve this issue.
pip install matplotlib --force-reinstall

https://stackoverflow.com/questions/47126186/matplotlib-cant-load-ft2font-on-windows-10
https://stackoverflow.com/questions/48603413/in-ft2font-can-not-load-face

**Comment by molyswu** [comment]
my  os is the ubuntu18.04.
